### ISSUE TITLE
Add stripcomments

### ISSUE THREAD

**Issue by kirillDanshin** [valyala/quicktemplate#1]
We have cool `stripspace` feature already, and maybe it's time to add `stripcomments` to remove html comments?

**Comment by valyala** [comment]
I reluctant adding `stripcomments` tag to `quicktemplate`, because of the following reasons:

* `Quicktemplate` already supports `{% comment %}` tag, which may be used for inserting inline comments inside template functions. These comments won't trap into the output. There is also a possibility to insert Go comments inside `{% code %}` tag:

```qtpl
{% code // one-liner comment %}

{% code
// this is multi-line
// comment
%}

{% code
/*
  this is yet another
  multi-line comment
*/
%}
```
* Stripping `<!-- html comments -->` is very specific requirement, since these comments are usually intended to be passed to the client.

* `stripcomments` function may be easily implemented when needed:

```go
import "regexp"

var htmlCommentRegexp = regexp.MustCompile("<!--(?:(?s).*?)-->")

func stripHTMLComments(s string) string {
    return htmlCommentRegexp.ReplaceAllLiteralString(s, "")
}
```

Put this function in Go file with arbitrary name located in the folder with templates.

Then this function may be used inside `quicktemplate` templates:

```qtpl
foo produces html comments
{% func foo() %}
    <!-- this comment
must be
stripped
  -->
  This should trap to output
  <!-- this is yet another comment to be stripped -->
{% endfunc %}

{% func Bar() %}
   foo contents without html comments: {%s= stripHTMLComments(foo()) %}
   foo contents with html comments: {%= foo() %}
{% endfunc %}
```

**Comment by kirillDanshin** [comment]
First of all, thanks for quick response.

---

> ```go
>  var htmlCommentRegexp = regexp.MustCompile("")
> ```

this regex will match special IE comments like

```html
<!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
```
So, if you want to save it (and by default you want) you might want to use this line instead:
```go
var htmlCommentRegexp = regexp.MustCompile("<!--[^[if](?:.|\s)*?-->")
```
of this
```go
var htmlCommentRegexp = regexp.MustCompile("(?:\s{2,})|(?:<!--[^[if](?:.*|\s)*?-->)")
```
---
Also, can I add my own keyword like `code` and others, for example `stripcomments` etc.?

**Comment by valyala** [comment]
> Also, can I add my own keyword like code and others, for example stripcomments etc.?

Currently `quicktemplate` doesn't support custom tags, but it may be implemented in the future. I'd recommend filing a separate issue for this feature.
