### ISSUE TITLE
Best Practice: Code organization

### ISSUE THREAD

**Issue by slot** [valyala/quicktemplate#21]
Hi @valyala,

thank you for the great project. What is your best practice organizing the files? Do you usually commit the templates and compiled templates in your projects or just the templates and compile e.g. during CI just before test/build?

Thanks for your advice. 

Sven

**Comment by valyala** [comment]
The initial plan was to put template files in a dedicated folders and then just import them as go packages. For instance, let the following folder structure exists:
```
src/
   cmd/
       app1/   <- here is the main package for app1
       app2/   <- here is the main package for app2
    package1/ <- here is package1, which may be used by any app from cmd
    ....
    packageN/ <- here is packageN, which may be used by any app from cmd
    templates/ <- here is a package with templates (qtpl files)
```
Then all the templates must be placed inside `templates` folder. But this solution didn't work properly in practice, since sometimes templates are used only inside the given package and require internal struct and functions from this package. So now we resorted to mixing `.qtpl` files with the ordinary `.go` files in package folders. And this works great for our use cases :)

**Comment by valyala** [comment]
> Do you usually commit the templates and compiled templates in your projects or just the templates and compile e.g. during CI just before test/build?

We usually commit compiled templates in our projects. This gives us two benefits:
- Reproducible builds, since the build doesn't depend on `qtc` version.
- There is no need to install `qtc` on build machines - plain `go build` is enough.
